#' procFulcrum
#'
#' \code{procFulcrum} processes raw Fulcrum data read into R with the \code{readFulcrum} function.
#' Processing consists of dropping unused variables, renaming variables for joining, and adding flags to collection data.
#'
#' @param data A list of dataframes generated by the \code{readFulcrum} function.
#' @return A list of up to five processed dataframes.
#' \tabular{ll}{
#' nematode_field_sampling_proc \tab a processed dataframe from the nematode_field_sampling.csv\cr
#' nematode_field_sampling_sample_photo_proc \tab a processed dataframe from the nematode_field_sampling_sample_photo.csv\cr
#' nematode_isolation_proc \tab a processed dataframe from the nematode_isolation.csv\cr
#' nematode_isolation_s_labeled_plates_proc \tab a processed dataframe from the nematode_isolation_s_labeled_plates.csv\cr
#' nematode_isolation_photos_proc \tab a processed dataframe from the nematode_isolation_photos.csv\cr
#' }
#' @import dplyr
#' @importFrom runner streak_run
#' @export

procFulcrum <- function(data) {
  # find names of data
  data_names <- names(data)

  # make processed data list
  proc_data <- list()

  # process nematode_field_sampling
  if("nematode_field_sampling" %in% data_names) {
    message("Processing nematode_field_sampling")
    nematode_field_sampling_proc <- data$nematode_field_sampling %>%
      dplyr::mutate(c_label = stringr::str_to_upper(c_label)) %>%
      # name created_by to specify who picked up the sample
      dplyr::rename(collection_by = created_by,
                    collection_fulcrum_latitude = latitude,
                    collection_fulcrum_longitude = longitude,
                    fulcrum_altitude = gps_altitude,
                    collection_local_time = time) %>%
      dplyr::select(-updated_at,
                    -system_created_at,
                    -system_updated_at,
                    -date,
                    -sample_photo_caption, # not needed here, can bring in from photo export
                    -sample_photo_url) %>% # make custom urls later with function
      # this is UTC time (very important if you want to convert to local time)
      dplyr::mutate(collection_datetime_UTC = lubridate::ymd_hms(created_at, tz = "UTC")) %>%
      # again this is UTC date (very important if you want to convert to local date)
      dplyr::mutate(collection_date_UTC = lubridate::date(created_at)) %>%
      dplyr::select(-created_at) %>%
      # Flag Fahrenheit observations and fix in proc
      dplyr::mutate(flag_substrate_temperature = ifelse(substrate_temperature > 40, TRUE, FALSE),
                    proc_substrate_temperature = ifelse(substrate_temperature > 40,
                                                        FtoC(substrate_temperature),
                                                        substrate_temperature)) %>%
      # Rename sub_temp with raw prefix
      dplyr::rename(raw_substrate_temperature = substrate_temperature) %>%
      # Fix ambient temp F to C
      dplyr::mutate(flag_ambient_temperature = ifelse(ambient_temperature_c > 40, TRUE, FALSE),
                    proc_ambient_temperature = ifelse(ambient_temperature_c > 40,
                                                      FtoC(ambient_temperature_c),
                                                      ambient_temperature_c)) %>%
      # Rename ambient_temp with raw prefix
      dplyr::rename(raw_ambient_temperature = ambient_temperature_c) %>%
      # force ambient temp to numeric
      dplyr::mutate(raw_ambient_temperature = as.numeric(raw_ambient_temperature)) %>%
      # add flags for runs of temperature data
      dplyr::arrange(collection_datetime_UTC) %>%
      dplyr::mutate(flag_ambient_temperature_run = ifelse(ambient_humidity == dplyr::lag(ambient_humidity) &
                                                            raw_ambient_temperature == dplyr::lag(raw_ambient_temperature) & gridsect == "no", TRUE, FALSE),
                    run_length = runner::streak_run(flag_ambient_temperature_run),
                    flag_ambient_temperature_run = ifelse((run_length > 3 & flag_ambient_temperature_run == TRUE) |
                                     (lead(run_length, n = 2L) >= 3 & flag_ambient_temperature_run == TRUE), TRUE, FALSE)) %>%
      dplyr::select(-run_length) %>%
      # flag duplicated C-labels
      dplyr::group_by(c_label) %>%
      dplyr::mutate(flag_duplicated_c_label_field_sampling = ifelse(dplyr::n() > 1, TRUE, FALSE)) %>%
      dplyr::ungroup() %>%
      # looks for commas in the sample_photo name
      dplyr::mutate(flag_unusual_sample_photo_num = ifelse(is.na(stringr::str_count(sample_photo, pattern = ",")) |
                                                             stringr::str_count(sample_photo, pattern = ",") != 0, TRUE, FALSE)) %>%
      # break apart mutliple sample photos. This takes the first sample photo and warns if additional photos are discarded
      tidyr::separate(col = sample_photo, into = c("sample_photo1", "sample_photo2", "sample_photo3"), sep = ",", extra = "drop", fill = "right")

    # add to processed list
    proc_data["nematode_field_sampling_proc"] <- list(nematode_field_sampling_proc)
  }

  # Process nematode_field_sampling_sample_photo
  if("nematode_field_sampling_sample_photo" %in% data_names) {
    message("Processing nematode_field_sampling_sample_photo")
    nematode_field_sampling_sample_photo_proc <- data$nematode_field_sampling_sample_photo %>%
      dplyr::group_by(fulcrum_parent_id) %>% # group to find best precision among photos
      dplyr::arrange(exif_gps_dop) %>%
      dplyr::ungroup() %>%
      dplyr::distinct(fulcrum_parent_id, .keep_all = T) %>%
      dplyr::mutate(best_exif_gps_dop = TRUE) %>%
      dplyr::select(fulcrum_id, exif_gps_latitude, exif_gps_longitude, exif_gps_altitude, best_exif_gps_dop, exif_gps_dop, best_sample_photo_caption = caption)

    # add to list
    proc_data["nematode_field_sampling_sample_photo_proc"] <- list(nematode_field_sampling_sample_photo_proc)
  }

  # Process nematode_isolation
  if("nematode_isolation" %in% data_names) {
    message("Processing nematode_isolation")
    nematode_isolation_proc <- data$nematode_isolation %>%
      dplyr::group_by(c_label) %>%
      dplyr::mutate(flag_duplicated_isolation_for_c_label = ifelse(dplyr::n() > 1, TRUE, FALSE)) %>% # could use count here without grouping?
      dplyr::ungroup() %>%
      dplyr::select(c_label_id = c_label,
                    flag_duplicated_isolation_for_c_label,
                    isolation_id = fulcrum_id,
                    isolation_datetime_UTC = system_created_at,
                    isolation_by = created_by,
                    worms_on_sample,
                    approximate_number_of_worms,
                    isolation_date_UTC = date,
                    isolation_local_time = time, # Is this actually local time? or is it UTC?
                    isolation_latitude = latitude,
                    isolation_longitude = longitude)

    # add to list
    proc_data["nematode_isolation_proc"] <- list(nematode_isolation_proc)
  }

  if("nematode_isolation_s_labeled_plates" %in% data_names) {
    message("Processing nematode_isolation_s_labeled_plates")
    nematode_isolation_s_labeled_plates_proc <- data$nematode_isolation_s_labeled_plates %>%
      dplyr::select(fulcrum_parent_id, s_label) %>%
      # flag duplicated S-labels
      dplyr::group_by(s_label) %>%
      dplyr::mutate(flag_duplicated_s_label_isolation_s_labeled_plates = ifelse(dplyr::n() > 1, TRUE, FALSE),
                    flag_duplicated_s_label_isolation_s_labeled_plates = ifelse(flag_duplicated_s_label_isolation_s_labeled_plates == TRUE &
                                                                                  is.na(s_label), FALSE, flag_duplicated_s_label_isolation_s_labeled_plates)) %>%
      dplyr::ungroup() %>%
      # flag missing S-labels
      dplyr::mutate(flag_missing_s_label_isolation_s_labeled_plates = ifelse(is.na(s_label), TRUE, FALSE))

    # add to list
    proc_data["nematode_isolation_s_labeled_plates_proc"] <- list(nematode_isolation_s_labeled_plates_proc)
  }

  if("nematode_isolation_s_labeled_plates" %in% data_names) {
    message("Processing nematode_isolation_photos")
    # read in isolation photos dataframe
    nematode_isolation_photos_proc <- data$nematode_isolation_photos

    # add to list
    proc_data["nematode_isolation_photos_proc"] <- list(nematode_isolation_photos_proc)
  }

  # return list
  return(proc_data)
}
