#' procFulcrum
#'
#' \code{procFulcrum} processes raw Fulcrum data read into R with the \code{readFulcrum} function.
#' Processing consists of dropping unused variables, renaming variables for joining, and adding flags to collection data.
#'
#' @param data A list of dataframes generated by the \code{readFulcrum} function.
#' @return A list of five named data frames.
#' \tabular{ll}{
#' nematode_field_sampling \tab a processed dataframe from the nematode_field_sampling.csv\cr
#' nematode_field_sampling_sample_photo \tab a processed dataframe from the nematode_field_sampling_sample_photo.csv\cr
#' nematode_isolation \tab a processed dataframe from the nematode_isolation.csv\cr
#' nematode_isolation_s_labeled_plates \tab a processed dataframe from the nematode_isolation_s_labeled_plates.csv\cr
#' nematode_isolation_photos \tab a processed dataframe from the nematode_isolation_photos.csv\cr
#' }
#' @export

procFulcrum <- function(data) {
  proc_data <- NULL
  # Read collection data
  nematode_field_sampling_proc <- data[[1]] %>%
    dplyr::mutate(c_label = stringr::str_to_upper(c_label)) %>%
    # name created_by to specify who picked up the sample
    dplyr::rename(collection_by = created_by,
                  collection_fulcrum_latitude = latitude,
                  collection_fulcrum_longitude = longitude,
                  fulcrum_altitude = gps_altitude,
                  collection_local_time = time) %>%
    dplyr::select(-updated_at,
                  -system_created_at,
                  -system_updated_at,
                  -date) %>%
    # choose one sample photo only. This takes the first sample photo and warns if additional photos are discarded
    tidyr::separate(col = sample_photo, into = "sample_photo", sep = ",", extra = "warn") %>%
    # this is UTC time (very important if you want to convert to local time)
    dplyr::mutate(collection_datetime_UTC = lubridate::ymd_hms(created_at, tz = "UTC")) %>%
    # again this is UTC date (very important if you want to convert to local date)
    dplyr::mutate(collection_date_UTC = lubridate::date(created_at)) %>%
    dplyr::select(-created_at) %>%
    # Flag Fahrenheit observations and fix in proc
    dplyr::mutate(flag_substrate_temperature = ifelse(substrate_temperature > 40, TRUE, FALSE),
                  proc_substrate_temperature = ifelse(substrate_temperature > 40,
                                                      FtoC(substrate_temperature),
                                                      substrate_temperature)) %>%
    # Rename sub_temp with raw prefix
    dplyr::rename(raw_substrate_temperature = substrate_temperature) %>%
    # Fix ambient temp F to C
    dplyr::mutate(flag_ambient_temperature = ifelse(ambient_temperature_c > 40, TRUE, FALSE),
                  proc_ambient_temperature = ifelse(ambient_temperature_c > 40,
                                                    FtoC(ambient_temperature_c),
                                                    ambient_temperature_c)) %>%
    # Rename ambient_temp with raw prefix
    dplyr::rename(raw_ambient_temperature = ambient_temperature_c) %>%
    # force ambient temp to numeric
    dplyr::mutate(raw_ambient_temperature = as.numeric(raw_ambient_temperature)) %>%
    # add flags for runs of temperature data
    dplyr::arrange(collection_datetime_UTC) %>%
    dplyr::mutate(flag_ambient_temperature_run = (ambient_humidity == dplyr::lag(ambient_humidity)) &
                    (raw_ambient_temperature == dplyr::lag(raw_ambient_temperature))
                  & (gridsect == "no")) %>%
    # flag duplicated C-labels
    dplyr::group_by(c_label) %>%
    dplyr::mutate(flag_duplicated_c_label_field_sampling = ifelse(n() > 1, TRUE, FALSE)) %>%
    dplyr::ungroup()

  # Read collection photo position data (exif)
  nematode_field_sampling_sample_photo_proc <- data[[2]] %>%
    dplyr::select(fulcrum_id, exif_gps_latitude, exif_gps_longitude, exif_gps_altitude)

  # Read isolation data
  nematode_isolation_proc <- data[[3]] %>%
    dplyr::select(c_label_id = c_label,
                  isolation_id = fulcrum_id,
                  isolation_datetime_UTC = system_created_at,
                  isolation_by = created_by,
                  worms_on_sample,
                  approximate_number_of_worms,
                  isolation_date_UTC = date,
                  isolation_local_time = time, # Is this actually local time? or is it UTC?
                  isolation_latitude = latitude,
                  isolation_longitude = longitude)

  # Read s_labeled plate data
  nematode_isolation_s_labeled_plates_proc <- data[[4]] %>%
    dplyr::select(fulcrum_parent_id, s_label) %>%
    # flag duplicated S-labels
    dplyr::group_by(s_label) %>%
    dplyr::mutate(flag_duplicated_s_label_isolation_s_labeled_plates = ifelse(n() > 1, TRUE, FALSE)) %>%
    dplyr::ungroup() %>%
    # flag missing S-labels
    dplyr::mutate(flag_missing_s_label_isolation_s_labeled_plates = ifelse(is.na(s_label), TRUE, FALSE))

  # read in isolation photos dataframe
  nematode_isolation_photos_proc <- data[[5]]

  # make proc_data list
  proc_data <- list("nematode_field_sampling_proc" = nematode_field_sampling_proc,
                    "nematode_field_sampling_sample_photo_proc" = nematode_field_sampling_sample_photo_proc,
                    "nematode_isolation_proc" = nematode_isolation_proc,
                    "nematode_isolation_s_labeled_plates_proc" = nematode_isolation_s_labeled_plates_proc,
                    "nematode_isolation_photos_proc" = nematode_isolation_photos_proc)
  # return list
  return(proc_data)
}
